# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Matti Pohjanvirta # Your name.
email: # Your email

# Use consideration when using these, publicly available contact information
# and place of residence is not something you might want to have.
address: # Your address
phone: # Your phone number
dob: # Your date of birth
image: avatar.JPG
title: Developer # Your title eg. Writer, programmer, welder, etc.
github_username:  Grrandi # Your github username
linkedin_url: # Your linkedin public url
twitter_handle: # Your twitter handle

abstract: > # Here you should write a brief summary about yourself.
   I'm an intermediate programmer interested in many different technologies. I'm just starting my professional career
   and I have lots and lots to learn, but I'm eager to get there. Recently I've been working as a system designer for
   the University of Jyväskylä focusing mainly on web development.
description: > # Description for the site
  Curriculum Vitae
theme: theme-ocean-orange # Color theme for the site.

# Localization
projects: Personal projects
skills: Skills
languages: Language
hobbies: Hobbies
experience: Experience
education: Education
email_text: Email
phone_text: Phone
dob_text: Date of birth
address_text: Address

baseurl: ""

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass