# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: User MacUserino
email: user.userino@example.com
description: > # this means to ignore newlines until "baseurl:"
  Personal cover page for this test user.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  foobarbizbuzhopefullynotrealuser
linkedin_url: https://linkedin.com/profile/sample
twitter_handle:

# Build settings
markdown: kramdown
