# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: User MacUserino # Your name.
email: user.userino@example.com #
title: Awesomeness Expert # Your title eg. Writer, programmer, welder, etc.
abstract: > # Here you should write a brief summary about yourself in professional context. Don't make it too long.
   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a tortor eget mi interdum dignissim. Pellentesque molestie felis vitae leo scelerisque tempus. Duis posuere mi non nisl gravida faucibus. Donec nulla lacus, sodales vel gravida id, mollis sit amet quam. Vivamus placerat aliquet est, vel egestas nulla porttitor ut. Quisque quis justo nec nisi faucibus vehicula. Sed urna nibh, placerat vel vehicula eget, laoreet sit amet lorem. Nam lectus arcu, sodales at eros et, finibus vehicula risus. Vivamus mollis congue ipsum, sit amet efficitur felis. Cras eu accumsan mi. Cras efficitur ornare sem, eget molestie lacus interdum et. Vivamus luctus neque non eros congue, ut hendrerit lorem vestibulum. Nullam erat sem, sagittis id lacinia finibus, faucibus eu libero. Vivamus in purus et nunc tempor aliquam quis vitae risus.
description: > # Description for the site
  Personal cover page for this test user.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  foobarbizbuzhopefullynotrealuser
linkedin_url: https://linkedin.com/profile/sample
twitter_handle:

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass